name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: cd frontend && npm ci
      
      - name: Run all tests with coverage
        run: cd frontend && npm test -- --coverage --watchAll=false
      
      - name: Run integration tests
        run: cd frontend && npm test -- integration.test.js --watchAll=false
      
      - name: Report results
        if: success()
        run: echo "✅ All 64 tests passing"